name: release gem

on:
  release:
    types: [published]

jobs:
  build:
    name: Build + Publish Gem
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: build gem
      run: |
        gem build cfn_monitor.gemspec

    - name: Publish gem to rubygems
      uses: dawidd6/action-publish-gem@v1
      with:
        api_key: ${{secrets.RUBYGEMS_API_KEY}}
        github_token: ${{secrets.GITHUB_TOKEN}}